### ISSUE TITLE
Component not work on Angular 9

### ISSUE THREAD

**Issue by frozendo** [adedayo/ngx-liquid-gauge#16]
Hi,

I tried to update my application to angular 9, but when loading the screen with the component an error occurred:

**Could not read the undefined property 'nativeElement'**

![image](https://user-images.githubusercontent.com/13833689/86868904-f7f21700-c0ab-11ea-9737-950021cdeb14.png)

The component was working well with version 7 of angular.
Did you have this error? Should this component work at angular 9?

**Comment by Tzahi12345** [comment]
Getting this error too!

It seems to be this line from the compiled `ngx-liquid-gauge.js`:

```
createChart() {
        /** @type {?} */
        const element = this.gauge.nativeElement; // <- this is the problem line
        ...
}
```

The mechanism to retrieve an element in Angular changed as [ViewChild now requires a static field](https://angular.io/guide/static-query-migration). Likely what's causing this issue is the lack of the static field in [line 12 of ngx-liquid-gauge.component.ts](https://github.com/adedayo/ngx-liquid-gauge/blob/master/projects/ngx-liquid-gauge/src/lib/ngx-liquid-gauge.component.ts#L12) ([source](https://stackoverflow.com/questions/56845380/cannot-read-property-native-element-of-undefined-angular-8)). Either that, or the createChart() should be called in ngAfterViewInit [instead of ngOnInit](https://github.com/adedayo/ngx-liquid-gauge/blob/master/projects/ngx-liquid-gauge/src/lib/ngx-liquid-gauge.component.ts#L39) ([source](https://stackoverflow.com/a/47986327/8088021))

I honestly can't tell which of these is causing the issue as I'm not sure how to set up the development environment to test this. Hope the dev sees this and tries out these solutions, may be an easy fix.

EDIT:

Solved!! It was the second issue, that is the `this.createChart();` has to be called in ngAfterViewInit rather than ngOnInit. Check out my PR (#18) which addresses this issue.

**Comment by adedayo** [comment]
@frozendo and @Tzahi12345. i have now hopefully fixed those issues and added support for angular 10. The changes are in version 2.0.5 

I have tested locally and it seems to work. Kindly let me know if this resolves the issues for you. In the meantime, I shall be closing this issue. Please reopen if there are still issues.
